// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCp25YT7OnrBQ5j_5HSAuefWfefl98cb4',
    appId: '1:1072329852364:web:2ce7608126101774e90969',
    messagingSenderId: '1072329852364',
    projectId: 'flutterdb-e2167',
    authDomain: 'flutterdb-e2167.firebaseapp.com',
    storageBucket: 'flutterdb-e2167.appspot.com',
    measurementId: 'G-VWPV1QBFV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNknL7oGSHUG6uQLRByLOI1FMgxRp0f0',
    appId: '1:1072329852364:android:642168a512e20bd8e90969',
    messagingSenderId: '1072329852364',
    projectId: 'flutterdb-e2167',
    storageBucket: 'flutterdb-e2167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28SDgFtO0LTkKH2yJ0pfvsmoTm4D-vJE',
    appId: '1:1072329852364:ios:678894a0e387a1b0e90969',
    messagingSenderId: '1072329852364',
    projectId: 'flutterdb-e2167',
    storageBucket: 'flutterdb-e2167.appspot.com',
    iosBundleId: 'com.example.firebaseJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB28SDgFtO0LTkKH2yJ0pfvsmoTm4D-vJE',
    appId: '1:1072329852364:ios:678894a0e387a1b0e90969',
    messagingSenderId: '1072329852364',
    projectId: 'flutterdb-e2167',
    storageBucket: 'flutterdb-e2167.appspot.com',
    iosBundleId: 'com.example.firebaseJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCp25YT7OnrBQ5j_5HSAuefWfefl98cb4',
    appId: '1:1072329852364:web:6b215a1095d05402e90969',
    messagingSenderId: '1072329852364',
    projectId: 'flutterdb-e2167',
    authDomain: 'flutterdb-e2167.firebaseapp.com',
    storageBucket: 'flutterdb-e2167.appspot.com',
    measurementId: 'G-LDLY9YGCC4',
  );
}
